version: '3.8'

services:
  api-rest:
    image: api_rim_cache:1.0.0
    container_name: api-rim_cache
    ports:
      - "5000:8080"  # Host:Container -> Tu API en localhost:5000 apunta al puerto 8080 del contenedor
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped
    networks:
      - api-network

networks:
  api-network:
    driver: bridge